// https://developer.mozilla.org/en-US/docs/Web/API/Event

/** @external {AnimationEvent} https://developer.mozilla.org/en-US/docs/Web/API/AnimationEvent */
/** @external {AudioProcessingEvent} https://developer.mozilla.org/en-US/docs/Web/API/AudioProcessingEvent */
/** @external {BeforeUnloadEvent} https://developer.mozilla.org/en-US/docs/Web/API/BeforeUnloadEvent */
/** @external {BlobEvent} https://developer.mozilla.org/en-US/docs/Web/API/BlobEvent */
/** @external {ClipboardEvent} https://developer.mozilla.org/en-US/docs/Web/API/ClipboardEvent */
/** @external {CloseEvent} https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent */
/** @external {CompositionEvent} https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent */
/** @external {CustomEvent} https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent */
/** @external {DeviceLightEvent} https://developer.mozilla.org/en-US/docs/Web/API/DeviceLightEvent */
/** @external {DeviceMotionEvent} https://developer.mozilla.org/en-US/docs/Web/API/DeviceMotionEvent */
/** @external {DeviceOrientationEvent} https://developer.mozilla.org/en-US/docs/Web/API/DeviceOrientationEvent */
/** @external {DeviceProximityEvent} https://developer.mozilla.org/en-US/docs/Web/API/DeviceProximityEvent */
/** @external {DragEvent} https://developer.mozilla.org/en-US/docs/Web/API/DragEvent */
/** @external {ErrorEvent} https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent */
/** @external {FetchEvent} https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent */
/** @external {FocusEvent} https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent */
/** @external {GamepadEvent} https://developer.mozilla.org/en-US/docs/Web/API/GamepadEvent */
/** @external {HashChangeEvent} https://developer.mozilla.org/en-US/docs/Web/API/HashChangeEvent */
/** @external {IDBVersionChangeEvent} https://developer.mozilla.org/en-US/docs/Web/API/IDBVersionChangeEvent */
/** @external {InputEvent} https://developer.mozilla.org/en-US/docs/Web/API/InputEvent */
/** @external {KeyboardEvent} https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent */
/** @external {MediaStreamEvent} https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamEvent */
/** @external {MessageEvent} https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent */
/** @external {MouseEvent} https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent */
/** @external {MutationEvent} https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent */
/** @external {OfflineAudioCompletionEvent} https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioCompletionEvent */
/** @external {PageTransitionEvent} https://developer.mozilla.org/en-US/docs/Web/API/OfflineAudioCompletionEvent */
/** @external {PointerEvent} https://developer.mozilla.org/en-US/docs/Web/API/PageTransitionEvent */
/** @external {PopStateEvent} https://developer.mozilla.org/en-US/docs/Web/API/PopStateEvent */
/** @external {ProgressEvent} https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent */
/** @external {RTCDataChannelEvent} https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannelEvent */
/** @external {RTCIdentityErrorEvent} https://developer.mozilla.org/en-US/docs/Web/API/RTCIdentityErrorEvent */
/** @external {RTCIdentityEvent} https://developer.mozilla.org/en-US/docs/Web/API/RTCIdentityEvent */
/** @external {RTCPeerConnectionIceEvent} https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnectionIceEvent */
/** @external {StorageEvent} https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent */
/** @external {SVGEvent} https://developer.mozilla.org/en-US/docs/Web/API/SVGEvent */
/** @external {TimeEvent} https://developer.mozilla.org/en-US/docs/Web/API/TimeEvent */
/** @external {TouchEvent} https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent */
/** @external {TransitionEvent} https://developer.mozilla.org/en-US/docs/Web/API/TransitionEvent */
/** @external {UIEvent} https://developer.mozilla.org/en-US/docs/Web/API/UIEvent */
/** @external {UserProximityEvent} https://developer.mozilla.org/en-US/docs/Web/API/UserProximityEvent */
/** @external {WebGLContextEvent} https://developer.mozilla.org/en-US/docs/Web/API/WebGLContextEvent */
/** @external {WheelEvent} https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent */
